DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    token TEXT NOT NULL,
    photo TEXT NOT NULL,
    phone TEXT NOT NULL,
    position TEXT NOT NULL,
    alt_token TEXT
);

DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_title TEXT NOT NULL,
    message_body TEXT NOT NULL,
    out_token TEXT NOT NULL,
    in_token TEXT NOT NULL
)
